const industry = [
  {
    value: 0,
    label: 'A农、林、牧、渔业'
  }, {
    value: 1,
    label: 'B采矿业'
  }, {
    value: 2,
    label: 'C制造业'
  }, {
    value: 3,
    label: 'D电力、热力、燃气及水生产和供应业'
  }, {
    value: 4,
    label: 'E建筑业'
  }, {
    value: 5,
    label: 'F交通运输、仓储和邮政业'
  }, {
    value: 6,
    label: 'G信息传输、软件和信息技术服务业'
  }, {
    value: 7,
    label: 'H批发和零售业'
  }, {
    value: 8,
    label: 'I住宿和餐饮业'
  }, {
    value: 9,
    label: 'J金融业'
  }, {
    value: 10,
    label: 'K房地产业'
  }, {
    value: 11,
    label: 'L租赁和商务服务业'
  }, {
    value: 12,
    label: 'M科学研究和技术服务业'
  }, {
    value: 13,
    label: 'N水利、环境和公共设施管理业'
  }, {
    value: 14,
    label: 'O居民服务、修理和其他服务业'
  }, {
    value: 15,
    label: 'P教育'
  }, {
    value: 16,
    label: 'Q卫生和社会工作'
  }, {
    value: 17,
    label: 'R文化、体育和娱乐业'
  }, {
    value: 18,
    label: 'S公共管理、社会保障和社会组织'
  }, {
    value: 19,
    label: 'T国际组织'
  }
]
export default industry
